accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns: list[path] = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('home/', views.home, name='home_content'),
    path('signup/', views.register, name='signup'),
]

budget_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from accounts import views as accounts_views
from expenses import views as expenses_views
from incomes import views as incomes_views
from new_app import views as new_app_views

urlpatterns = [
    # URLs для home
    path('', home_views.home_content, name='home_content'),
    path('home/', home_views.home, name='home'),
    path('income-list/', home_views.income_list, name='income_list'),
    path('expense-list/', expenses_views.expense_list, name='expense_list'),
    path('expense-chart/', expenses_views.expense_chart, name='expense_chart'),
    path('expense-income-chart/', home_views.expense_income_chart, name='expense_income_chart'),
    path('budget-planning/', home_views.budget_planning, name='budget_planning'),
    path('add-budget/', home_views.budget_planning, name='add_budget'),
    path('financial-tips/', home_views.financial_tips, name='financial_tips'),
    path('add-expense/', expenses_views.add_expense, name='add_expense'),
    path('profile/', home_views.profile, name='profile'),
    path('delete-income/<int:id>/', home_views.delete_income, name='delete_income'),
    path('delete-expense/<int:id>/', expenses_views.delete_expense, name='delete_expense'),
    path('income-chart/', home_views.income_chart, name='income_chart'),
    path('signup/', home_views.signup, name='signup'),
    path('delete-budget/<int:id>/', home_views.delete_budget, name='delete_budget'),
    path('register/', accounts_views.register, name='register'),
    path('login/', accounts_views.user_login, name='login'),
    # URLs для accounts
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),  # Добавлено пространство имен и include

    # URLs для expenses
    path('expenses/add/', expenses_views.add_expense, name='add_expense'),
    path('expenses/chart/', expenses_views.expense_chart, name='expense_chart'),
    path('expenses/delete/<int:expense_id>/', expenses_views.delete_expense, name='delete_expense'),
    path('expenses/list/', expenses_views.expense_list, name='expense_list'),
    path('expenses/home_content/', expenses_views.home_content_view, name='home_content'),

    # URLs для incomes
    path('incomes/add/', incomes_views.add_income, name='add_income'),
    path('incomes/list/', incomes_views.income_list, name='income_list'),

    # URLs для new_app
    path('new_app/', new_app_views.index, name='index'),


    # Admin URL
    path('admin/', admin.site.urls),

]

home/forms.py
from django import forms
from decimal import Decimal, InvalidOperation
from .models import Expense, Income


class ExpenseForm(forms.ModelForm):
    """
    Form for creating and updating Expense instances.
    """

    class Meta:
        model = Expense
        fields = ['name', 'source', 'amount', 'date']

    def clean_amount(self) -> Decimal:
        """
        Validate the amount field.

        Returns:
            Decimal: The validated amount.

        Raises:
            forms.ValidationError: If the amount is invalid.
        """
        amount = self.cleaned_data.get('amount')
        try:
            amount = Decimal(str(amount).replace(',', '.'))
        except InvalidOperation:
            raise forms.ValidationError('Некоректне значення суми. Воно повинно бути числом з десятковою точкою.')

        if amount <= 0:
            raise forms.ValidationError("Сума повинна бути більшою за нуль.")

        if len(str(amount).replace('.', '').replace('-', '')) > 10:
            raise forms.ValidationError("Сума не повинна перевищувати 10 символів.")

        return amount


class IncomeForm(forms.ModelForm):
    """
    Form for creating and updating Income instances.
    """

    class Meta:
        model = Income
        fields = ['name', 'source', 'amount', 'date']

    def clean_amount(self) -> Decimal:
        """
        Validate the amount field.

        Returns:
            Decimal: The validated amount.

        Raises:
            forms.ValidationError: If the amount is invalid.
        """
        amount = self.cleaned_data.get('amount')
        try:
            amount = Decimal(str(amount).replace(',', '.'))
        except InvalidOperation:
            raise forms.ValidationError('Некоректне значення суми. Воно повинно бути числом з десятковою точкою.')

        if amount <= 0:
            raise forms.ValidationError("Сума повинна бути більшою за нуль.")

        if len(str(amount).replace('.', '').replace('-', '')) > 10:
            raise forms.ValidationError("Сума не повинна перевищувати 10 символів.")

        return amount

    def clean(self) -> dict:
        """
        Validate all fields.

        Returns:
            dict: The cleaned data.

        Raises:
            forms.ValidationError: If any field is invalid.
        """
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        source = cleaned_data.get('source')
        amount = cleaned_data.get('amount')
        date = cleaned_data.get('date')

        if not name or not source or not amount or not date:
            raise forms.ValidationError("Всі поля є обов'язковими для заповнення.")

        return cleaned_data

home/views.py
import matplotlib.pyplot as plt
import io
import base64
import logging
import datetime
import random
import matplotlib.colors as mcolors
from django.db.models import Sum
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from expenses.models import Expense
from incomes.models import Income
from .models import Budget
from incomes.forms import IncomeForm
from .forms import ExpenseForm
User = get_user_model()
logger = logging.getLogger(__name__)


def home(request: HttpRequest) -> HttpResponse:
    """Render the home page."""
    return render(request, 'home.html')

def home_content(request: HttpRequest) -> HttpResponse:
    """Render the home content page."""
    return render(request, 'home_content.html')

@login_required
def delete_expense(request, id):
    """
    Handle deleting an expense.

    Args:
        request (HttpRequest): The HTTP request.
        id (int): The ID of the expense to delete.

    Returns:
        HttpResponse: The HTTP response redirecting to the expense list page.
    """
    expense = get_object_or_404(Expense, id=id)
    expense.delete()
    return redirect('expense_list')

def profile(request: HttpRequest) -> HttpResponse:
    """Render the profile page."""
    return render(request, 'profile.html')

@login_required
def income_list(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('income_list')
        else:
            return render(request, 'income_list.html', {'form': form, 'incomes': Income.objects.all()})
    else:
        form = IncomeForm()

    return render(request, 'income_list.html', {'form': form, 'incomes': Income.objects.all()})


@login_required
def delete_income(request: HttpRequest, id: int) -> HttpResponseRedirect:
    """Handle the deletion of an income."""
    income = get_object_or_404(Income, id=id)
    income.delete()
    return redirect('income_list')

@login_required
def add_expense(request: HttpRequest) -> HttpResponse:
    """
    Handle adding a new expense.

    Args:
        request (HttpRequest): The HTTP request.

    Returns:
        HttpResponse: The HTTP response with the rendered add expense page.
    """
    if request.method == 'POST':
        name = request.POST['name']
        category = request.POST['category']
        amount = request.POST['amount']
        date = request.POST['date']

        if not name or not category or not amount or not date:
            raise ValidationError("All fields are required.")

        Expense.objects.create(name=name, source=category, amount=amount, date=date)
        return redirect('expense_list')
    return render(request, 'expenses/add_expense.html')

@login_required
def add_income(request: HttpRequest) -> HttpResponse:
    """Handle the addition of a new income."""
    if request.method == 'POST':
        name = request.POST['name']
        category = request.POST['category']
        amount = request.POST['amount']
        date = request.POST['date']

        if not name or not category or not amount or not date:
            raise ValidationError("Всі поля обов'язкові для заповнення.")

        Income.objects.create(name=name, category=category, amount=amount, date=date)
        return redirect('income_list')
    return render(request, 'incomes/add_income.html')


@login_required
def budget_planning(request: HttpRequest) -> HttpResponse:
    """Handle budget planning and display current budgets."""
    if request.method == 'POST':
        if 'delete_budget' in request.POST:
            budget_id = request.POST['delete_budget']
            budget = get_object_or_404(Budget, id=budget_id)
            budget.delete()
        else:
            name = request.POST['name']
            category = request.POST['category']
            amount = request.POST['amount']
            date = request.POST['date']
            Budget.objects.create(name=name, category=category, amount=amount, date=date)
        return redirect('budget_planning')
    budgets = Budget.objects.all()
    total_income = sum(budget.amount for budget in budgets if budget.category == 'Доход')
    total_expense = sum(budget.amount for budget in budgets if budget.category == 'Витрати')
    remaining_budget = total_income - total_expense
    return render(request, 'budget_planning.html', {
        'budgets': budgets,
        'total_income': total_income,
        'total_expense': total_expense,
        'remaining_budget': remaining_budget
    })

@login_required
def delete_budget(request: HttpRequest, id: int) -> HttpResponseRedirect:
    """Handle the deletion of a budget."""
    budget = get_object_or_404(Budget, id=id)
    budget.delete()
    return redirect('budget_planning')

@login_required
def expense_list(request: HttpRequest) -> HttpResponse:
    """
    Handle displaying and adding expenses.

    Args:
        request (HttpRequest): The HTTP request.

    Returns:
        HttpResponse: The HTTP response with the rendered expense list page.
    """
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('expense_list')
        else:
            return render(request, 'expense_list.html', {'form': form, 'expenses': Expense.objects.all()})
    else:
        form = ExpenseForm()

    expenses = Expense.objects.all()
    return render(request, 'expense_list.html', {'form': form, 'expenses': expenses})

@login_required
def expense_chart(request: HttpRequest) -> HttpResponse:
    """Render a bar chart of expenses by source for a selected month."""
    if 'month' in request.GET:
        selected_month = request.GET['month']
    else:
        selected_month = datetime.datetime.now().strftime('%Y-%m')

    year, month = map(int, selected_month.split('-'))
    expenses = Expense.objects.filter(date__year=year, date__month=month)

    unique_sources = set(expense.source for expense in expenses)
    random.seed(42)
    colors = random.sample(list(mcolors.CSS4_COLORS.values()), len(unique_sources))
    source_color_map = {source: color for source, color in zip(unique_sources, colors)}

    for expense in expenses:
        expense.color = source_color_map[expense.source]

    source_totals = expenses.values('source').annotate(total=Sum('amount')).order_by('source')
    plt.figure(figsize=(10, 5))
    plt.bar([item['source'] for item in source_totals], [item['total'] for item in source_totals],
            color=[source_color_map[item['source']] for item in source_totals])
    plt.xlabel('Джерела', fontsize=14, fontweight='bold')
    plt.ylabel('Сума', fontsize=14, fontweight='bold')
    plt.title('Розподіл витрат по джерелах', fontsize=16, fontweight='bold')
    plt.xticks(rotation=45)
    plt.grid(True, linestyle='--', alpha=0.7)

    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    plt.close()
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()
    graphic = base64.b64encode(image_png).decode('utf-8')

    ukr_months = {
        1: "Січень", 2: "Лютий", 3: "Березень", 4: "Квітень",
        5: "Травень", 6: "Червень", 7: "Липень", 8: "Серпень",
        9: "Вересень", 10: "Жовтень", 11: "Листопад", 12: "Грудень"
    }
    month_name = f"{ukr_months[month]} {year}"

    return render(request, 'expense_chart.html',
                  {'expenses': expenses, 'month': selected_month, 'month_name': month_name, 'graphic': graphic})

@login_required
def financial_tips(request: HttpRequest) -> HttpResponse:
    """Render the financial tips page."""
    return render(request, 'financial_tips.html')


@login_required
def income_chart(request: HttpRequest) -> HttpResponse:
    """
    Render a bar chart of incomes by source for a selected month.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object with the rendered income chart page.
    """
    if 'month' in request.GET:
        selected_month = request.GET['month']
    else:
        selected_month = datetime.datetime.now().strftime('%Y-%m')

    year, month = map(int, selected_month.split('-'))
    incomes = Income.objects.filter(date__year=year, date__month=month)

    unique_sources = set(income.source for income in incomes)
    random.seed(42)
    colors = random.sample(list(mcolors.CSS4_COLORS.values()), len(unique_sources))
    source_color_map = {source: color for source, color in zip(unique_sources, colors)}

    for income in incomes:
        income.color = source_color_map[income.source]

    source_totals = incomes.values('source').annotate(total=Sum('amount')).order_by('source')
    plt.figure(figsize=(10, 5))
    plt.bar([item['source'] for item in source_totals], [item['total'] for item in source_totals],
            color=[source_color_map[item['source']] for item in source_totals])
    plt.xlabel('Джерела доходу', fontsize=14, fontweight='bold')
    plt.ylabel('Сума', fontsize=14, fontweight='bold')
    plt.title('Розподіл доходів по джерелах', fontsize=16, fontweight='bold')
    plt.xticks(rotation=45)
    plt.grid(True, linestyle='--', alpha=0.7)

    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()
    graphic = base64.b64encode(image_png).decode('utf-8')

    ukr_months = {
        1: "Січень", 2: "Лютий", 3: "Березень", 4: "Квітень",
        5: "Травень", 6: "Червень", 7: "Липень", 8: "Серпень",
        9: "Вересень", 10: "Жовтень", 11: "Листопад", 12: "Грудень"
    }
    month_name = f"{ukr_months[month]} {year}"

templates/home.html
<!DOCTYPE html>
<html lang="uk">
<head>
    {% load static %}
    {% load i18n %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
    <div class="top-right-corner"> 
        {% if user.is_authenticated %} 
            <div class="auth-buttons"> 
                <form method="post" action="{% url 'accounts:logout' %}"> 
                    {% csrf_token %} 
                    <button type="submit" class="auth-button auth-button-logout">{% trans "Вийти" %}</button> 
                </form> 
            </div> 
        {% else %} 
            <div class="auth-buttons"> 
                <a href="{% url 'accounts:login' %}" class="auth-button auth-button-login">{% trans "Увійти" %}</a> 
                <a href="{% url 'accounts:register' %}" class="auth-button auth-button-signup">{% trans "Реєстрація" %}</a> 
            </div> 
        {% endif %} 
    </div>
    <div class="container-fluid">
        <div class="flex-container">
            <div class="flex-column flex-column--sidebar">
                <nav class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home_content' %}">{% trans "Головна" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'income_list' %}">{% trans "Доходи" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'expense_list' %}">{% trans "Витрати" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'income_chart' %}">{% trans "Графіки Доходів" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'expense_chart' %}">{% trans "Графіки Витрат" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'budget_planning' %}">{% trans "Планування бюджета" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'financial_tips' %}">{% trans "Фінансові поради" %}</a>
                    </li>
                </nav>
            </div>
            <div class="flex-column flex-column--main">
                <div id="content">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="row">
            <div class="col-md-3">
                <img src="{% static 'images/kiev.jpg' %}" alt="Київ" style="width: 125px; height: 125px; margin-bottom: 5px;">
                <div><strong>{% trans "Місцезнаходження:" %}</strong> <a href="https://www.google.com/maps?q=Київ,вулиця+Прикладна,123" target="_blank" style="color: white;"><i class="fas fa-map-marker-alt" style="margin-right: 5px;"></i>{% trans "Київ, вулиця Прикладна, 123" %}</a></div>
            </div>
            <div class="col-md-3">
                <img src="{% static 'images/telephone.jpg' %}" alt="Телефон" style="width: 125px; height: 125px; margin-bottom: 5px;">
                <div><strong>{% trans "Телефон:" %}</strong> +380 44 123 4567</div>
            </div>
            <div class="col-md-3">
                <img src="{% static 'images/calendar.jfif' %}" alt="Графік роботи" style="width: 125px; height: 125px; margin-bottom: 5px;">
                <div><strong>{% trans "Графік роботи:" %}</strong> {% trans "Пн-Пт з 8:00 до 19:00" %}</div>
            </div>
            <div class="col-md-3">
                <img src="{% static 'images/soc.seti.jpg' %}" alt="Соціальні мережі" style="width: 125px; height: 125px; margin-bottom: 5px;">
                <div><strong>{% trans "Соціальні мережі:" %}</strong>
                    <a href="https://www.facebook.com" target="_blank" style="color: white; margin-left: 5px;"><i class="fab fa-facebook"></i></a>
                    <a href="https://www.twitter.com" target="_blank" style="color: white; margin-left: 5px;"><i class="fab fa-twitter"></i></a>
                    <a href="https://www.linkedin.com" target="_blank" style="color: white; margin-left: 5px;"><i class="fab fa-linkedin"></i></a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const links = document.querySelectorAll('.nav-link');
            links.forEach(function(link) {
                link.addEventListener('click', function(e) {
                    e.preventDefault();
                    links.forEach(link => link.classList.remove('active'));
                    link.classList.add('active');
                    const targetUrl = link.getAttribute('href');
                    history.pushState(null, '', targetUrl);
                    fetch(targetUrl)
                        .then(response => response.text())
                        .then(html => {
                            const parser = new DOMParser();
                            const doc = parser.parseFromString(html, 'text/html');
                            const newContent = doc.querySelector('#content');
                            if (newContent) {
                                const contentElement = document.querySelector('#content');
                                if (contentElement) {
                                    contentElement.innerHTML = newContent.innerHTML;
                                }
                            }

                            if (targetUrl === "{% url 'home_content' %}") {
                                history.replaceState(null, '', '/home_content');
                            }
                        })
                        .catch(err => console.error('Failed to fetch page: ', err));
                });

                if (window.location.pathname === '/') {
                    const homeLink = document.querySelector('.nav-link[href="{% url 'home_content' %}"]');
                    if (homeLink) {
                        homeLink.classList.add('active');
                        history.replaceState(null, '', '/home_content');
                    }
                }
            });

            const monthSelect = document.getElementById('month');
            if (monthSelect) {
                const monthNames = ['Січень', 'Лютий', 'Березень', 'Квітень', 'Травень', 'Червень', 'Липень', 'Серпень', 'Вересень', 'Жовтень', 'Листопад', 'Грудень'];

                for (let i = 0; i < monthSelect.options.length; i++) {
                    const option = monthSelect.options[i];
                    const monthValue = option.value.split('-')[1];
                    const yearValue = option.value.split('-')[0];
                    option.text = `${monthNames[parseInt(monthValue) - 1]} ${yearValue}`;
                }
            }
        });
    </script>
</body>
</html>